# Generated by Django 4.2.2 on 2023-06-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group_director', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('number_student_initial', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('document_type', models.CharField(max_length=50)),
                ('document_number', models.IntegerField(default=0)),
                ('cohorte_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.cohorte')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('excuse', models.BooleanField(default=False)),
                ('excuse_support', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.students')),
            ],
        ),
    ]
